version: "3"
services:

  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: connectLoom
      MONGO_INITDB_ROOT_PASSWORD: connectLoom
    networks:
      - app-network


  # API (backend) service
  api:
    image: sarathchandran2000/connectloom
    container_name: server
    volumes:
      - node_modules:/app/node_modules
      - ./server:/app
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - app-network


  # Frontend service
  frontend:
    image: sarathchandran2000/connectloom-frontend
    container_name: frontend
    stdin_open: true
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
  # Nginx service
  # nginx:
  #   depends_on:
  #     - api
  #     - frontend
  #   restart: always
  #   build:
  #     dockerfile: dockerfile
  #     context: ./nginx
  #   ports:


  
